const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1) + min)

const CARDS = {
    colors: [
        '#0C76B2',
        '#EAAB00',
        '#EDB5B8',
        '#CED1BE',
        '#306750',
        '#8DB0C3',
        '#73626C',
        '#FE883E',
        '#F3E3D4'
    ],
    words: [
        ['Animal de estimação comum', 'Animal de estimação exótico'],
        ['Céu', 'Inferno'],
        ['Reto', 'Sinuoso'],
        ['Prefere gatos', 'Prefere cachorros'],
        ['Melhor online', 'Melhor Presencialmente'],
        ['Etiqueta', 'Educação'],
        ['Jogo subestimado', 'Jogo superestimado'],
        ['Dá uma sensação ruim', 'Dá uma sensação boa'],
        ['Fruta', 'Vegetal'],
        ['Difícil de fazer', 'Fácil de fazer'],
        ['Legal', 'Proibido'],
        ['Número baixo', 'Número alto'],
        ['Impotente', 'Poderoso'],
        ['Necessidade', 'Desejo'],
        ['Tempo perdido', 'Tempo bem aproveitado'],
        ['Assunto chato', 'Assunto fascinante'],
        ['Arte', 'Produto'],
        ['É tão ruim que é bom', 'Só é ruim mesmo'],
        ['Inacreditável', 'Plausível'],
        ['Beneficia só você', 'Beneficia todo mundo'],
        ['Habilidade subestimada', 'Habilidade superestimada'],
        ['O livro é melhor', 'O filme é melhor'],
        ['Pessoa muito tranquila', 'Pessoa muito preocupada'],
        ['Distopia', 'Utopia'],
        ['Inflexível', 'Flexível'],
        ['Nada saudável', 'Saudável'],
        ['Coisa normal de se ter', 'Coisa esquisita de se ter'],
        ['Bom hábito', 'Mau hábito'],
        ['Tem uma má reputação', 'Tem uma boa reputação'],
        ['Derivado', 'Original'],
        ['Fobia sem sentido', 'Fobia que faz sentido'],
        ['Supérfluo', 'Essencial'],
        ['Ciência', 'Pseudociência'],
        ['Sábio', 'Inteligente'],
        ['Não é arte', 'É arte'],
        ['Curiosidade', 'Interesse'],
        ['Charmoso', 'Sedutor'],
        ['Comida seca', 'Comida úmida'],
        ['Filme triste', 'Filme feliz'],
        ['Insosso', 'Saboroso'],
        ['Banda/músico de um sucesso só', 'Ícone pop'],
        ['Fofoca', 'Novidade'],
        ['Brega', 'Classudo'],
        ['Cor nada chamativa', 'Cor chamativa'],
        ['Seco', 'Úmido'],
        ['Introvertido', 'Extrovertido'],
        ['Difícil de achar', 'Fácil de achar'],
        ['Sabor de pizza ruim', 'Sabor de pizza bom'],
        ['Expectativa', 'Realidade'],
        ['Pequeno demais', 'Grande demais'],
        ['Sempre atrasado', 'Sempre pontual'],
        ['Muito mal remunerado', 'Muito bem remunerado'],
        ['Sem pelos', 'Peludo'],
        ['Substituível', 'Insubstituível'],
        ['Imóvel', 'Móvel'],
        ['Lugar para morar', 'Lugar para passar as férias'],
        ['Inútil', 'Útil'],
        ['Mau investimento', 'Bom investimento'],
        ['De baixa qualidade', 'De alta qualidade'],
        ['Descontrolado', 'Controlado'],
        ['Tradicional', 'Radical'],
        ['Vale muito dinheiro', 'Não vale um centavo'],
        ['Vício', 'Virtude'],
        ['Produção artesanal', 'Produção em massa'],
        ['Músico subestimado', 'Músico superestimado'],
        ['Sem importância', 'Importante'],
        ['Sessão da Tarde', 'Tela Quente'],
        ['Todo mundo gosta', 'Todo mundo finge que gosta'],
        ['Grifinória', 'Sonserina'],
        ['Parece um ser humano', 'Não parece um ser humano'],
        ['Feio', 'Bonito'],
        ['Suspense', 'Terror'],
        ['Modelo a ser seguido', 'Má influência'],
        ['Segredo', 'Conhecimento público'],
        ['Não vai viver até os cem', 'Vai viver até os cem'],
        ['Casual', 'Formal'],
        ['Historicamente importante', 'Historicamente irrelevante'],
        ['Pior atleta da história', 'Melhor atleta da história'],
        ['Animal feroz', 'Animal dócil'],
        ['Problema local', 'Problema global'],
        ['Filme que o Godzilla ia arruinar', 'Filme que o Godzilla ia melhorar'],
        ['Vingança', 'Justiça'],
        ['Cantada boa', 'Cantada ruim'],
        ['Lanchinho', 'Refeição'],
        ['Precisa experimentar para saber se é bom', 'Não precisa experimentar para saber se é bom'],
        ['Limitado', 'Infinito'],
        ['Doce ruim', 'Doce gostoso'],
        ['Ideia estúpida', 'Ideia brilhante'],
        ['Fácil de soletrar', 'Difícil de soletrar'],
        ['Evento diurno', 'Evento noturno'],
        ['Fraco', 'Forte'],
        ['Xingamento', 'Ofensa'],
        ['Parece inofensivo mas na verdade é perigoso', 'Parece perigoso mas na verdade é inofensivo'],
        ['Temporário', 'Permanete'],
        ['Filme ruim', 'Filme bom'],
        ['Popular', 'Elitista'],
        ['Precisa de um remake', 'Prefiro o original'],
        ['Básico', 'Estiloso'],
        ['Horizontal', 'Vertical'],
        ['Barato', 'Caro'],
        ['Perigoso', 'Seguro'],
        ['Antiético', 'Ético'],
        ['Personagem engraçado', 'Personagem sem graça'],
        ['Opcional', 'Obrigatório'],
        ['Emoji sem sentido', 'Emoji com duplo sentido'],
        ['Socialista', 'Capitalista'],
        ['Nada abraçável', 'Abraçável'],
        ['Difícil de lembrar', 'Fácil de lembrar'],
        ['Pessoa em quem você daria uma surra', 'Pessoa que daria uma surra em você'],
        ['Parte do corpo inútil', 'Parte do corpo útil'],
        ['Cansado', 'Enérgico'],
        ['Vive pouco', 'Vive muito'],
        ['Anti-higiênico', 'Higiênico'],
        ['Livro subestimado', 'Livro superestimado'],
        ['Incolor', 'Colorido'],
        ['Passado', 'Futuro'],
        ['Fácil de matar', 'Difícil de matar'],
        ['Pensamento profundo', 'Pensamento raso'],
        ['Fracasso', 'Obra-prima'],
        ['Papo na roda de amigos', 'Papo no almoço de família'],
        ['Instável', 'Estável'],
        ['Ator ruim', 'Ator bom'],
        ['Bênção', 'Maldição'],
        ['Joga muito', 'Fala muito'],
        ['Culturalmente significativo', 'Culturalmente insignificativo'],
        ['Passatempo chato', 'Passatempo interessante'],
        ['Programa de TV ruim', 'Programa de TV bom'],
        ['Fazer agora', 'Deixar para depois'],
        ['Progressista', 'Conservador'],
        ['Fato pouco conhecido', 'Fato muito conhecido'],
        ['Heterogêneo', 'Homogêneo'],
        ['Inculto', 'Culto'],
        ['Esperado', 'Inesperado'],
        ['Modinha', 'Clássico'],
        ['Difícil de usar', 'Fácil de usar'],
        ['Coisa que ninguém faz', 'Coisa que todo mundo faz'],
        ['Música ruim', 'Música boa'],
        ['Pessoa desinteressante', 'Pessoa divertida'],
        ['Pouco calórico', 'Muito calórico'],
        ['Comida que faz sujeira', 'Comida que não faz sujeira'],
        ['Duvidoso', 'Confiável'],
        ['Disciplina escolar chata', 'Disciplina escolar interessante'],
        ['Imperdoável', 'Perdoável'],
        ['Atividade mental', 'Atividade física'],
        ['Natural', 'Artificial'],
        ['Ditadura', 'Democracia'],
        ['Acontece devagar', 'Acontece de repente'],
        ['Superpoder bom', 'Superpoder ruim'],
        ['Star Wars', 'Star Trek'],
        ['Filme de ação', 'Filme de aventura'],
        ['Bem', 'Mal'],
        ['Talento', 'Habilidade'],
        ['Insuficiente', 'Exagerado'],
        ['Assunto simples', 'Assunto complicado'],
        ['Espécie em perigo de extinção', 'Espécie superpopulosa'],
        ['Filme subestimado', 'Filme superestimado'],
        ['Pessoa do mal', 'Pessoa do bem'],
        ['Não divido com ninguém', 'Divido com todo mundo'],
        ['Sem graça', 'Engraçado'],
        ['Encontro ruim', 'Encontro bom'],
        ['Personagem da Disney superestimado', 'Personagem da Disney subestimado'],
        ['Mau', 'Bom'],
        ['Música triste', 'Música alegre'],
        ['Arredondado', 'Pontiagudo'],
        ['Não é sanduíche', 'É um sanduíche'],
        ['Exige sorte', 'Exige habilidade'],
        ['Inclusivo', 'Excludente'],
        ['Áspero', 'Liso']
    ],
    randomColors: function () {
        let firstColor = randomInt(0, this.colors.length-1)
        let secondColor = randomInt(0, this.colors.length-1)
        if (firstColor == secondColor) {
            secondColor = secondColor - 1 < 0 ? this.colors[this.colors.length-1] : secondColor - 1
        }
        return [this.colors[firstColor], this.colors[secondColor]]
    },
    randomWords: function () {
        return this.words[randomInt(0, this.words.length-1)]
    }
}